### ISSUE TITLE
CANNOT LINK EXECUTABLE

### ISSUE THREAD

**Issue by RanchhodRamani** [jaiobs/OptiVideoEditor-for-android#7]
Testing in android emulator Android R(10.0+) 30 API version.

I am facing the issue as below in above device. same code run into an emulator.

`CANNOT LINK EXECUTABLE "/data/user/0/com.obs.marveleditor/files/ffmpeg": "/data/user/0/com.obs.marveleditor/files/ffmpeg" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)` 

Tested in Android Q(10) 29 Api version with the real device and working fine.

Please advise on the same so we can run the app without any issue. 
Thanks.

**Comment by gopinathan1202** [comment]
Updated to API 29 version. Kindly check in real device.
