### ISSUE TITLE
App is not working after changing targetsdk to 29 or after upgrading code to AndroidX

### ISSUE THREAD

**Issue by surya-official** [jaiobs/OptiVideoEditor-for-android#8]
Please resolve it fast

**Comment by SuryaChundawat** [comment]
Getting same issue. App is not working on complie 29

**Comment by SuryaChundawat** [comment]
Its using ffmpeg and ffmpeg is directly not supported in android 10.

**Comment by Bhardwajraju** [comment]
It's not working in Android 10

**Comment by gopinathan1202** [comment]
Issue fixed.

**Comment by adityaprajapati5687** [comment]
still, the issue is there, it is not working  if you set the target SDK to 29, because playstore needs minimum target and compile SDK to be 29

**Comment by gopinathan1202** [comment]
@adityaprajapati5687 I changed target SDK to 30 itself. App is working fine in Android 10. Did you clone development branch and tested?

**Comment by adityaprajapati5687** [comment]
@gopinathan1202   Thanks, now checked the development code, and working fine, thanks a lot.

**Comment by sagar1garg** [comment]
@gopinathan1202 when I use the development branch it works fine but when I import the project into another project I get  error=13, Permission denied.
Could you please let me know what exactly did you change to get it to work on api 30 and above?
